# Generated by Django 5.1.2 on 2024-10-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_format', models.CharField(choices=[('vinyl', 'Vinyl'), ('cd', 'CD'), ('digital', 'Digital')], default='Digital', max_length=50)),
                ('record_type', models.CharField(choices=[('lp', 'LP'), ('ep', 'EP'), ('compilation', 'Compilation'), ('mixtape', 'Mixtape')], default='LP', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('genre', models.CharField(choices=[('Rap/Hip-Hop', 'Rap/Hip-Hop'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Soul/Funk', 'Soul/Funk'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Country', 'Country'), ('Pop', 'Pop'), ('Electronic', 'Electronic')], default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('categories', models.ManyToManyField(related_name='products', to='store.category')),
            ],
        ),
    ]
